name: nowdots_social_news
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.3.1
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1
  http: ^1.2.1
  intl: ^0.19.0
  flutter_otp_text_field: ^1.1.3+2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  get_it: ^7.7.0
  image_picker: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true

  assets:
    #logo
    - assets/logos/nowdots_logo.png
    - assets/logos/nowfoodie_logo.png
    - assets/logos/nowher_logo.png
    - assets/logos/nowhype_logo.png
    - assets/logos/nowplay_logo.png
    - assets/logos/nowsports_logo.png

    #images
    - assets/images/forgot_password_image.png
    - assets/images/signup_images.png
    - assets/images/signin_images.png
    - assets/images/anonymous-avatar.png

    #icons
    - assets/icons/home_outline.svg
    - assets/icons/home_filled.svg
    - assets/icons/notification_outline.svg
    - assets/icons/notification_filled.svg
    - assets/icons/news_outline.svg
    - assets/icons/news_filled.svg
    - assets/icons/setting_outline.svg
    - assets/icons/setting_filled.svg
    - assets/icons/google_icon.svg
    - assets/icons/apple_icon.svg
    - assets/icons/comment_outline.svg
    - assets/icons/down_vote_outline.svg
    - assets/icons/down_vote_filled.svg
    - assets/icons/up_vote_outline.svg
    - assets/icons/up_vote_filled.svg
    - assets/icons/forward.svg
    - assets/icons/thumb_down_outline.svg
    - assets/icons/thumb_down_filled.svg
    - assets/icons/thumb_up_outline.svg
    - assets/icons/thumb_up_filled.svg
    - assets/icons/bookmark_outline.svg

    #data dummy
    - assets/data_dummy/dummy_feed.json


  fonts:
    - family: Proxima Nova
      fonts:

          #thin
        - asset: assets/fonts/Proxima Nova/proxima_nova_thin.otf
          weight: 100
        - asset: assets/fonts/Proxima Nova/proxima_nova_thin_italic.otf
          weight: 100
          style: italic

          # light
        - asset: assets/fonts/Proxima Nova/proxima_nova_light.otf
          weight: 300
        - asset: assets/fonts/Proxima Nova/proxima_nova_light_italic.otf
          weight: 300
          style: italic

          # regular
        - asset: assets/fonts/Proxima Nova/proxima_nova_regular.otf
          weight: 400
        - asset: assets/fonts/Proxima Nova/proxima_nova_regular_italic.otf
          weight: 400
          style: italic

          # bold
        - asset: assets/fonts/Proxima Nova/proxima_nova_bold.otf
          weight: 700
        - asset: assets/fonts/Proxima Nova/proxima_nova_bold_italic.otf
          weight: 700
          style: italic
          
          #extra bold
        - asset: assets/fonts/Proxima Nova/proxima_nova_extrabold.otf
          weight: 800

          # black
        - asset: assets/fonts/Proxima Nova/proxima_nova_black.otf
          weight: 900
        - asset: assets/fonts/Proxima Nova/proxima_nova_black_italic.otf
          weight: 900
          style: italic

    - family: Segoe UI
      fonts:
          # light (extra light based on flutter fontWeight documentation)
        - asset: assets/fonts/Segoe UI/segoe_ui_light.ttf
          weight: 200
        - asset: assets/fonts/Segoe UI/segoe_ui_light_italic.ttf
          weight: 200
          style: italic

          # semilight (light based on flutter fontWeight documentation)
        - asset: assets/fonts/Segoe UI/segoe_ui_semilight.ttf
          weight: 300
        - asset: assets/fonts/Segoe UI/segoe_ui_semilight_italic.ttf
          weight: 300
          style: italic

          # regular
        - asset: assets/fonts/Segoe UI/segoe_ui.ttf
          weight: 400
        - asset: assets/fonts/Segoe UI/segoe_ui_italic.ttf
          weight: 400
          style: italic

          # semibold
        - asset: assets/fonts/Segoe UI/segoe_ui_semibold.ttf
          weight: 600
        - asset: assets/fonts/Segoe UI/segoe_ui_semibold_italic.ttf
          weight: 600
          style: italic

          # bold
        - asset: assets/fonts/Segoe UI/segoe_ui_bold.ttf
          weight: 700
        - asset: assets/fonts/Segoe UI/segoe_ui_bold.ttf
          weight: 700
          style: italic

          # black
        - asset: assets/fonts/Segoe UI/segoe_ui_black.ttf
          weight: 900
        - asset: assets/fonts/Segoe UI/segoe_ui_black_italic.ttf
          weight: 900
          style: italic
        
  
